### ISSUE TITLE
Coding Style

### ISSUE THREAD

**Issue by miterfrants** [LiangYingC/Meet-Trail-Right-Project#14]
https://github.com/LiangYingC/Meet-Trail-Right-Project/blob/d91cb7eaedeafca45b12a2011b56a3febe3dc4a5/src/components/pages/Home/Home.jsx#L190

可以考慮用一下 eslint，雖然我自覺得沒有特別重要，但如果是多人開發的話建議有一至性的 coding style  像是 alignment 或是引號要用單引還是雙引號。

**Comment by LiangYingC** [comment]
eslint & prettier 都裝啦，除了 coding style 統一外，也修正了一些錯誤，像是：

1. 部分沒有 key
2. 部分 img 沒有 alt
3. 用了 target="_blank" 但沒有帶上 rel="noreferrer"
4. 在 switch case 中宣告的變數，會影響到另一個 case 
5. 刪除沒有用到的變數
6. 刪除沒有用到的大括號
7. 刪除沒有用的 if condition
8. 刪除沒有用到的 import
9. 整合重複的 import 路徑
10. ......。

其實這些錯誤目前都沒有影響到上線的功能，但能讓未來維運 code 時更便利囉。

https://github.com/LiangYingC/Meet-Trail-Right-Project/blob/master/.eslintrc.json

https://github.com/LiangYingC/Meet-Trail-Right-Project/blob/master/.prettierrc

以上，所以 close。
