### ISSUE TITLE
SEO-Friendly URL 

### ISSUE THREAD

**Issue by miterfrants** [LiangYingC/Meet-Trail-Right-Project#15]
https://github.com/LiangYingC/Meet-Trail-Right-Project/blob/d91cb7eaedeafca45b12a2011b56a3febe3dc4a5/src/routes/index.js#L27

https://moz.com/learn/seo/url

**Comment by miterfrants** [comment]
建議改成 trail-create 或是 trail_create，前者優於後者（不知道現在還是不是這樣，很久以前有文章這樣寫）

**Comment by miterfrants** [comment]
雖然這個 URL 不需要 SEO

**Comment by LiangYingC** [comment]
對哦這個 URL 不太需要 SEO，故先 close，Thx
