### ISSUE TITLE
寫一份 README.md

### ISSUE THREAD

**Issue by barry800414** [LiangYingC/Meet-Trail-Right-Project#6]
裡面可以包含幾項內容：
- Introduction：介紹這個專案是幹嘛的，可以錄螢幕操作做成 GIF 當 demo
- Development Guide：
  - 如果要 local 端跑起來，系統需求是什麼、要下什麼指令
  - 專案的資料夾結構
  - API documentation 要去哪邊找、DB Schema 的文件在哪邊
  - 如果要回報 issue ，是否有什麼格式、流程
- Contributing Guide：如果要幫送 PR，有沒有要遵循什麼格式
- Testing：要跑專案的測試要怎麼跑
- Demo site：放個 demo site 的網址

**Comment by LiangYingC** [comment]
已完成基本款
